# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hero Guest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hero Guest
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'Hero GuestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hero GuestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
